### ISSUE TITLE
Term cache not cleaned properly in `quick_update_terms_count` function

### ISSUE THREAD

**Issue by Souptik2001** [Automattic/lightweight-term-count-update#20]
Hi,

I am facing an issue when using this plugin with a persistent object cache.
So, the problem here is that the term cache is not cleaned after updating(that is in this case incrementing or decrementing) the term count.

The problem is actually in the `quick_update_terms_count` function which calls the `clean_term_cache` function at the last, but the parameters passed to the function arguments seem to be wrong.

According to the function definition of [clean_term_cache](https://github.com/WordPress/wordpress-develop/blob/6.0.2/src/wp-includes/taxonomy.php#L3546-L3595), if the second argument(that is taxonomy value) is not empty then the first argument is expected to be `term_id` and if the second argument is empty then the first argument is expected to be `term_taxonomy_id`.
But [here](https://github.com/Automattic/lightweight-term-count-update/blob/master/lightweight-term-count-update.php#L264) in the `quick_update_terms_count` the `clean_term_cache` function is called with `term_taxonomy_id`, while also passing the taxonomy name as the second argument.
And for this reason, the cache is tried to be cleared with the wrong term ID(as the ID passed is term taxonomy ID), and so the cache cleaning fails, and the count doesn't update on the cache.

Please let me know if I misunderstood the issue, or if any more clarity is needed.

I am happy to raise a PR, if someone can confirm if this is really a bug.

Thanks!

**Comment by renatonascalves** [comment]
I recently run into the same issue on a site hosted on VIP.com. I'm guessing this is affecting all sites hosted there since they bundle this plugin into the `mu-plugins`.

Here is a temporary fix I used. 

```php
/**
 * Update term counts when term relationships are added or deleted.
 *
 * Temporary fix.
 *
 * @param int          $object_id Object ID.
 * @param array|string $tt_ids    Array of taxonomy term IDs or taxonomy term ID.
 */
function handle_term_relationship_change( $object_id, $tt_ids ) {

	if ( ! is_array( $tt_ids ) ) {
		$tt_ids = [ absint( $tt_ids ) ];
	}

	$tt_ids = wp_parse_id_list( $tt_ids );

	clean_term_cache( $tt_ids, '', false );
}
add_action( 'added_term_relationship', __NAMESPACE__ . '\handle_term_relationship_change', 11, 2 );
add_action( 'deleted_term_relationships', __NAMESPACE__ . '\handle_term_relationship_change', 11, 2 );
```

**Comment by mboynes** [comment]
Yes, `clean_term_cache()` is being called incorrectly here. Looks like that was my mistake, I inadvertently [updated the function call to add the taxonomy since we had it available](https://github.com/Automattic/lightweight-term-count-update/pull/2/commits/f3a4c88d089adc6231cac514612d3a6bab734bf5). I can fix that.

With regards to the scope of this issue, I _think_ this would only impact sites that never [split terms](https://make.wordpress.org/core/2015/02/16/taxonomy-term-splitting-in-4-2-a-developer-guide/) after WordPress 4.2 shipped in early 2015. After term splitting, tt_ids and term_ids should be the same value. It's possible I'm misremembering what old data looked like post-split, that was a long time ago 😅.
